const WELCOME_CHANNEL_ID = '556384703595413524';
const GENERAL_CHANNEL_ID = '548970921118007339';
const ACCOUNTABILITY_CHANNEL_ID = '557404903329234954';
const LOLFAP_CHANNEL_ID = '559924334534197249';
const ANNOUNCEMENT_CHANNEL_ID = '558569083168227338';
const EMERGENCY_CHANNEL_ID = '561652383755796490';

const WELCOME_CHANNEL_NAME = 'welcome';
const GENERAL_CHANNEL_NAME = 'general';
const ACCOUNTABILITY_CHANNEL_NAME = 'accountability';
const LOLFAP_CHANNEL_NAME = 'lolfap';
const ANNOUNCEMENT_CHANNEL_NAME = 'accouncements';
const EMERGENCY_CHANNEL_NAME = 'emergency';

const WELCOME_CHANNEL_DESCRIPTION = 'Welcome to the channel.';
const GENERAL_CHANNEL_DESCRIPTION = 'General chat about anything, really.';
const ACCOUNTABILITY_CHANNEL_DESCRIPTION = "Where you'll post your daily accountability message.";
const LOLFAP_CHANNEL_DESCRIPTION = 'Funny things related to porn recovery.';
const ANNOUNCEMENT_CHANNEL_DESCRIPTION = 'NeverFap Deluxe related accouncements.';
const EMERGENCY_CHANNEL_DESCRIPTION = "Support if you're feeling urges of any kind.";

module.exports = {
  WELCOME_CHANNEL_ID,
  GENERAL_CHANNEL_ID,
  ACCOUNTABILITY_CHANNEL_ID,
  LOLFAP_CHANNEL_ID,
  ANNOUNCEMENT_CHANNEL_ID,
  EMERGENCY_CHANNEL_ID,

  WELCOME_CHANNEL_NAME,
  GENERAL_CHANNEL_NAME,
  ACCOUNTABILITY_CHANNEL_NAME,
  LOLFAP_CHANNEL_NAME,
  ANNOUNCEMENT_CHANNEL_NAME,
  EMERGENCY_CHANNEL_NAME,

  WELCOME_CHANNEL_DESCRIPTION,
  GENERAL_CHANNEL_DESCRIPTION,
  ACCOUNTABILITY_CHANNEL_DESCRIPTION,
  LOLFAP_CHANNEL_DESCRIPTION,
  ANNOUNCEMENT_CHANNEL_DESCRIPTION,
  EMERGENCY_CHANNEL_DESCRIPTION,
};