// Command list
const RULES_COMMAND = "rules";
const COMMANDS_COMMAND = "commands";
const CHANNELS_COMMAND = "channels";
const ACCOUNTABILITY_COMMAND = "accountability";
const CHEATSHEET_COMMAND = "cheatsheet";
const EMERGENCY_COMMAND = "emergency";
// const SET_STREAK_COMMAND = "set-streak";
// const PROGRESS_COMMAND = "progress";

const RULES_COMMAND_DESCRIPTION = "Server rules.";
const COMMANDS_COMMAND_DESCRIPTION = "List all commands.";
const CHANNELS_COMMAND_DESCRIPTION = "List all channels.";
const ACCOUNTABILITY_COMMAND_DESCRIPTION = "#accountability channel rules.";
const CHEATSHEET_COMMAND_DESCRIPTION = "Healthy Coping Mechanism cheatsheet.";
const EMERGENCY_COMMAND_DESCRIPTION = "Display #emergency urge procedure.";
// const SET_STREAK_COMMAND_DESCRIPTION = "Set your current PMO streak.";
// const PROGRESS_COMMAND_DESCRIPTION = 'Learn more about your progress!';

module.exports = {
  RULES_COMMAND,
  COMMANDS_COMMAND,
  CHANNELS_COMMAND,
  ACCOUNTABILITY_COMMAND,
  CHEATSHEET_COMMAND,
  EMERGENCY_COMMAND,
  // SET_STREAK_COMMAND,
  // PROGRESS_COMMAND,

  RULES_COMMAND_DESCRIPTION,
  COMMANDS_COMMAND_DESCRIPTION,
  CHANNELS_COMMAND_DESCRIPTION,
  ACCOUNTABILITY_COMMAND_DESCRIPTION,
  CHEATSHEET_COMMAND_DESCRIPTION,
  EMERGENCY_COMMAND_DESCRIPTION,
  // SET_STREAK_COMMAND_DESCRIPTION,
  // PROGRESS_COMMAND_DESCRIPTION,
}
