// Command list
const RULES_COMMAND = "rules";
const HELP_COMMAND = "help";
const COMMANDS_COMMAND = "commands";
const CHANNELS_COMMAND = "channels";
const ACCOUNTABILITY_COMMAND = "accountability";
const ACCOUNTABILITY_EXAMPLE_COMMAND = "example";
const CHEATSHEET_COMMAND = "cheatsheet";
const ANTI_CHEATSHEET_COMMAND = "anti-cheatsheet";
const EMERGENCY_COMMAND = "emergency";
// const PROGRESS_COMMAND = "progress";

const RULES_COMMAND_DESCRIPTION = "list server rules";
const COMMANDS_COMMAND_DESCRIPTION = "list commands";
const CHANNELS_COMMAND_DESCRIPTION = "list channels";
const ACCOUNTABILITY_COMMAND_DESCRIPTION = "#accountability rules";
const ACCOUNTABILITY_EXAMPLE_COMMAND_DESCRIPTION = "#accountability post example";
const CHEATSHEET_COMMAND_DESCRIPTION = "Healthy Coping Mechanism cheatsheet";
const ANTI_CHEATSHEET_COMMAND_DESCRIPTION = "Unhealthy Coping Mechanism cheatsheet";
const EMERGENCY_COMMAND_DESCRIPTION = "get #emergency help";
// const PROGRESS_COMMAND_DESCRIPTION = 'Learn more about your progress!';

module.exports = {
  RULES_COMMAND,
  HELP_COMMAND,
  COMMANDS_COMMAND,
  CHANNELS_COMMAND,
  ACCOUNTABILITY_COMMAND,
  ACCOUNTABILITY_EXAMPLE_COMMAND,
  ANTI_CHEATSHEET_COMMAND,
  CHEATSHEET_COMMAND,
  EMERGENCY_COMMAND,
  // PROGRESS_COMMAND,

  RULES_COMMAND_DESCRIPTION,
  COMMANDS_COMMAND_DESCRIPTION,
  CHANNELS_COMMAND_DESCRIPTION,
  ACCOUNTABILITY_COMMAND_DESCRIPTION,
  ACCOUNTABILITY_EXAMPLE_COMMAND_DESCRIPTION,
  CHEATSHEET_COMMAND_DESCRIPTION,
  ANTI_CHEATSHEET_COMMAND_DESCRIPTION,
  EMERGENCY_COMMAND_DESCRIPTION,
  // PROGRESS_COMMAND_DESCRIPTION,
}
